INSERT INTO `products`(`name`, `price`, `image`) VALUES 
('Cheesburger Type 1','22.99','./templates/images/burger.webp'),
('Cheesburger Type 2','23.99','./templates/images/burger.webp'),
('Cheesburger Type 3','24.99','./templates/images/burger.webp'),
('Cheesburger Type 4','25.99','./templates/images/burger.webp'),
('Cheesburger Type 5','26.99','./templates/images/burger.webp'),
('Cheesburger Type 6','27.99','./templates/images/burger.webp'),
('Cheesburger Type 7','28.99','./templates/images/burger.webp'),
('Cheesburger Type 8','29.99','./templates/images/burger.webp'),
('Pizza Type 1','25.50','./templates/images/burger.webp'),
('Pizza Type 2','26.50','./templates/images/burger.webp'),
('Pizza Type 3','27.50','./templates/images/burger.webp'),
('Pizza Type 4','28.50','./templates/images/burger.webp'),
('Pizza Type 5','29.50','./templates/images/burger.webp'),
('Pizza Type 6','30.50','./templates/images/burger.webp'),
('Pizza Type 7','31.50','./templates/images/burger.webp'),
('Pizza Type 8','32.50','./templates/images/burger.webp')